export interface HtmlEncoding {
  value: string;
  description: string;
  number: number;
  code: string;
  friendlyCode: string;
  unicode: number;
}

export const htmlEncodings = [
  { value: '\t', description: 'tab', number: 9, code: '&#9;', friendlyCode: '&#tab;', unicode: 9 },
  { value: '\n', description: 'new line', number: 10, code: '&#10;', friendlyCode: '&#newline;', unicode: 0xa },
  { value: ' ', description: 'space', number: 32, code: '&#32;', friendlyCode: '&#nbsp;', unicode: 0x20 },
  { value: '!', description: 'exclamation mark', number: 33, code: '&#33;', friendlyCode: '', unicode: 0x21 },
  { value: '“', description: 'quotation mark', number: 34, code: '&#34;', friendlyCode: '&#quot;', unicode: 0x201c },
  { value: '"', description: 'quotation mark', number: 34, code: '&#34;', friendlyCode: '&#quot;', unicode: 0x22 },
  { value: '#', description: 'number sign', number: 35, code: '&#35;', friendlyCode: '', unicode: 0x23 },
  { value: '$', description: 'dollar sign', number: 36, code: '&#36;', friendlyCode: '', unicode: 0x24 },
  { value: '%', description: 'percent sign', number: 37, code: '&#37;', friendlyCode: '', unicode: 0x25 },
  { value: '&', description: 'ampersand', number: 38, code: '&#38;', friendlyCode: '&#amp;', unicode: 0x26 },
  { value: '‘', description: 'apostrophe #1', number: 39, code: '&#39;', friendlyCode: '', unicode: 0x2018 },
  { value: '`', description: 'apostrophe #2', number: 96, code: '&#96;', friendlyCode: '', unicode: 0x60 },
  { value: "'", description: 'apostrophe #3', number: 39, code: '&#39;', friendlyCode: '', unicode: 0x27 },
  { value: '(', description: 'opening/left parenthesis', number: 40, code: '&#40;', friendlyCode: '', unicode: 0x28 },
  { value: ')', description: 'closing/right parenthesis', number: 41, code: '&#41;', friendlyCode: '', unicode: 0x29 },
  { value: '*', description: 'asterisk', number: 42, code: '&#42;', friendlyCode: '', unicode: 0x2a },
  { value: '+', description: 'plus sign', number: 43, code: '&#43;', friendlyCode: '', unicode: 0x2b },
  { value: ',', description: 'comma', number: 44, code: '&#44;', friendlyCode: '', unicode: 0x2c },
  { value: '–', description: 'hyphen', number: 45, code: '&#45;', friendlyCode: '', unicode: 0x2013 },
  { value: '-', description: 'hyphen', number: 45, code: '&#45;', friendlyCode: '', unicode: 0x2d },
  { value: '.', description: 'period', number: 46, code: '&#46;', friendlyCode: '', unicode: 0x2e },
  { value: '/', description: 'slash', number: 47, code: '&#47;', friendlyCode: '', unicode: 0x2f },
  { value: '0', description: 'digit 0', number: 48, code: '&#48;', friendlyCode: '', unicode: 0x30 },
  { value: '1', description: 'digit 1', number: 49, code: '&#49;', friendlyCode: '', unicode: 0x31 },
  { value: '2', description: 'digit 2', number: 50, code: '&#50;', friendlyCode: '', unicode: 0x32 },
  { value: '3', description: 'digit 3', number: 51, code: '&#51;', friendlyCode: '', unicode: 0x33 },
  { value: '4', description: 'digit 4', number: 52, code: '&#52;', friendlyCode: '', unicode: 0x34 },
  { value: '5', description: 'digit 5', number: 53, code: '&#53;', friendlyCode: '', unicode: 0x35 },
  { value: '6', description: 'digit 6', number: 54, code: '&#54;', friendlyCode: '', unicode: 0x36 },
  { value: '7', description: 'digit 7', number: 55, code: '&#55;', friendlyCode: '', unicode: 0x37 },
  { value: '8', description: 'digit 8', number: 56, code: '&#56;', friendlyCode: '', unicode: 0x38 },
  { value: '9', description: 'digit 9', number: 57, code: '&#57;', friendlyCode: '', unicode: 0x39 },
  { value: ':', description: 'colon', number: 58, code: '&#58;', friendlyCode: '', unicode: 0x3a },
  { value: ';', description: 'semicolon', number: 59, code: '&#59;', friendlyCode: '', unicode: 0x3b },
  { value: '<', description: 'less-than', number: 60, code: '&#60;', friendlyCode: '&#lt;', unicode: 0x3c },
  { value: '=', description: 'equals sign', number: 61, code: '&#61;', friendlyCode: '', unicode: 0x3d },
  { value: '>', description: 'greater than', number: 62, code: '&#62;', friendlyCode: '&#gt;', unicode: 0x3e },
  { value: '?', description: 'question mark', number: 63, code: '&#63;', friendlyCode: '', unicode: 0x3f },
  { value: '@', description: 'at sign', number: 64, code: '&#64;', friendlyCode: '', unicode: 0x40 },
  { value: 'A', description: 'uppercase a', number: 65, code: '&#65;', friendlyCode: '', unicode: 0x41 },
  { value: 'B', description: 'uppercase b', number: 66, code: '&#66;', friendlyCode: '', unicode: 0x42 },
  { value: 'C', description: 'uppercase c', number: 67, code: '&#67;', friendlyCode: '', unicode: 0x43 },
  { value: 'D', description: 'uppercase d', number: 68, code: '&#68;', friendlyCode: '', unicode: 0x44 },
  { value: 'E', description: 'uppercase e', number: 69, code: '&#69;', friendlyCode: '', unicode: 0x45 },
  { value: 'F', description: 'uppercase f', number: 70, code: '&#70;', friendlyCode: '', unicode: 0x46 },
  { value: 'G', description: 'uppercase g', number: 71, code: '&#71;', friendlyCode: '', unicode: 0x47 },
  { value: 'H', description: 'uppercase h', number: 72, code: '&#72;', friendlyCode: '', unicode: 0x48 },
  { value: 'I', description: 'uppercase i', number: 73, code: '&#73;', friendlyCode: '', unicode: 0x49 },
  { value: 'J', description: 'uppercase j', number: 74, code: '&#74;', friendlyCode: '', unicode: 0x4a },
  { value: 'K', description: 'uppercase k', number: 75, code: '&#75;', friendlyCode: '', unicode: 0x4b },
  { value: 'L', description: 'uppercase l', number: 76, code: '&#76;', friendlyCode: '', unicode: 0x4c },
  { value: 'M', description: 'uppercase m', number: 77, code: '&#77;', friendlyCode: '', unicode: 0x4d },
  { value: 'N', description: 'uppercase n', number: 78, code: '&#78;', friendlyCode: '', unicode: 0x4e },
  { value: 'O', description: 'uppercase o', number: 79, code: '&#79;', friendlyCode: '', unicode: 0x4f },
  { value: 'P', description: 'uppercase p', number: 80, code: '&#80;', friendlyCode: '', unicode: 0x50 },
  { value: 'Q', description: 'uppercase q', number: 81, code: '&#81;', friendlyCode: '', unicode: 0x51 },
  { value: 'R', description: 'uppercase r', number: 82, code: '&#82;', friendlyCode: '', unicode: 0x52 },
  { value: 'S', description: 'uppercase s', number: 83, code: '&#83;', friendlyCode: '', unicode: 0x53 },
  { value: 'T', description: 'uppercase t', number: 84, code: '&#84;', friendlyCode: '', unicode: 0x54 },
  { value: 'U', description: 'uppercase u', number: 85, code: '&#85;', friendlyCode: '', unicode: 0x55 },
  { value: 'V', description: 'uppercase v', number: 86, code: '&#86;', friendlyCode: '', unicode: 0x56 },
  { value: 'W', description: 'uppercase w', number: 87, code: '&#87;', friendlyCode: '', unicode: 0x57 },
  { value: 'X', description: 'uppercase x', number: 88, code: '&#88;', friendlyCode: '', unicode: 0x58 },
  { value: 'Y', description: 'uppercase y', number: 89, code: '&#89;', friendlyCode: '', unicode: 0x59 },
  { value: 'Z', description: 'uppercase z', number: 90, code: '&#90;', friendlyCode: '', unicode: 0x5a },
  { value: '[', description: 'opening/left square bracket', number: 91, code: '&#91;', friendlyCode: '', unicode: 0x5b },
  { value: '\\', description: 'backslash', number: 92, code: '&#92;', friendlyCode: '', unicode: 0x5c },
  { value: ']', description: 'closing/right square bracket', number: 93, code: '&#93;', friendlyCode: '', unicode: 0x5d },
  { value: '^', description: 'caret', number: 94, code: '&#94;', friendlyCode: '', unicode: 0x5e },
  { value: '_', description: 'underscore', number: 95, code: '&#95;', friendlyCode: '', unicode: 0x5f },
  { value: '`', description: 'grave accent', number: 96, code: '&#96;', friendlyCode: '', unicode: 0x60 },
  { value: 'a', description: 'lowercase a', number: 97, code: '&#97;', friendlyCode: '', unicode: 0x61 },
  { value: 'b', description: 'lowercase b', number: 98, code: '&#98;', friendlyCode: '', unicode: 0x62 },
  { value: 'c', description: 'lowercase c', number: 99, code: '&#99;', friendlyCode: '', unicode: 0x63 },
  { value: 'd', description: 'lowercase d', number: 100, code: '&#100;', friendlyCode: '', unicode: 0x64 },
  { value: 'e', description: 'lowercase e', number: 101, code: '&#101;', friendlyCode: '', unicode: 0x65 },
  { value: 'f', description: 'lowercase f', number: 102, code: '&#102;', friendlyCode: '', unicode: 0x66 },
  { value: 'g', description: 'lowercase g', number: 103, code: '&#103;', friendlyCode: '', unicode: 0x67 },
  { value: 'h', description: 'lowercase h', number: 104, code: '&#104;', friendlyCode: '', unicode: 0x68 },
  { value: 'i', description: 'lowercase i', number: 105, code: '&#105;', friendlyCode: '', unicode: 0x69 },
  { value: 'j', description: 'lowercase j', number: 106, code: '&#106;', friendlyCode: '', unicode: 0x6a },
  { value: 'k', description: 'lowercase k', number: 107, code: '&#107;', friendlyCode: '', unicode: 0x6b },
  { value: 'l', description: 'lowercase l', number: 108, code: '&#108;', friendlyCode: '', unicode: 0x6c },
  { value: 'm', description: 'lowercase m', number: 109, code: '&#109;', friendlyCode: '', unicode: 0x6d },
  { value: 'n', description: 'lowercase n', number: 110, code: '&#110;', friendlyCode: '', unicode: 0x6e },
  { value: 'o', description: 'lowercase o', number: 111, code: '&#111;', friendlyCode: '', unicode: 0x6f },
  { value: 'p', description: 'lowercase p', number: 112, code: '&#112;', friendlyCode: '', unicode: 0x70 },
  { value: 'q', description: 'lowercase q', number: 113, code: '&#113;', friendlyCode: '', unicode: 0x71 },
  { value: 'r', description: 'lowercase r', number: 114, code: '&#114;', friendlyCode: '', unicode: 0x72 },
  { value: 's', description: 'lowercase s', number: 115, code: '&#115;', friendlyCode: '', unicode: 0x73 },
  { value: 't', description: 'lowercase t', number: 116, code: '&#116;', friendlyCode: '', unicode: 0x74 },
  { value: 'u', description: 'lowercase u', number: 117, code: '&#117;', friendlyCode: '', unicode: 0x75 },
  { value: 'v', description: 'lowercase v', number: 118, code: '&#118;', friendlyCode: '', unicode: 0x76 },
  { value: 'w', description: 'lowercase w', number: 119, code: '&#119;', friendlyCode: '', unicode: 0x77 },
  { value: 'x', description: 'lowercase x', number: 120, code: '&#120;', friendlyCode: '', unicode: 0x78 },
  { value: 'y', description: 'lowercase y', number: 121, code: '&#121;', friendlyCode: '', unicode: 0x79 },
  { value: 'z', description: 'lowercase z', number: 122, code: '&#122;', friendlyCode: '', unicode: 0x7a },
  { value: '{', description: 'opening/left curly brace', number: 123, code: '&#123;', friendlyCode: '', unicode: 0x7b },
  { value: '|', description: 'vertical bar', number: 124, code: '&#124;', friendlyCode: '', unicode: 0x7c },
  { value: '}', description: 'closing/right curly brace', number: 125, code: '&#125;', friendlyCode: '', unicode: 0x7d },
  { value: '~', description: 'tilde', number: 126, code: '&#126;', friendlyCode: '', unicode: 0x7e },
  { value: '€', description: 'euro sign', number: 128, code: '&#128;', friendlyCode: '', unicode: 0x20ac },
  { value: '‚', description: 'punctuation mark', number: 130, code: '&#130;', friendlyCode: '', unicode: 0x201a },
  { value: ',', description: 'punctuation mark', number: 130, code: '&#130;', friendlyCode: '', unicode: 0x2c },
  { value: 'ƒ', description: 'florin sign', number: 131, code: '&#131;', friendlyCode: '', unicode: 0x192 },
  { value: '„', description: 'quotation mark', number: 132, code: '&#132;', friendlyCode: '', unicode: 0x201e },
  { value: '…', description: 'horizontal ellipsis', number: 133, code: '&#133;', friendlyCode: '', unicode: 0x2026 },
  { value: '†', description: 'dagger', number: 134, code: '&#134;', friendlyCode: '', unicode: 0x2020 },
  { value: '‡', description: 'double dagger', number: 135, code: '&#135;', friendlyCode: '', unicode: 0x2021 },
  { value: 'ˆ', description: 'circumflex', number: 136, code: '&#136;', friendlyCode: '', unicode: 0x2c6 },
  { value: '^', description: 'circumflex', number: 136, code: '&#136;', friendlyCode: '', unicode: 0x5e },
  { value: '‰', description: 'per-mille', number: 137, code: '&#137;', friendlyCode: '', unicode: 0x2030 },
  { value: 'Š', description: 'latin capital letter s with caron', number: 138, code: '&#138;', friendlyCode: '', unicode: 0x160 },
  { value: '‹', description: 'single left angle quotation', number: 139, code: '&#139;', friendlyCode: '', unicode: 0x2039 },
  { value: '<', description: 'single left angle quotation', number: 139, code: '&#139;', friendlyCode: '', unicode: 0x3c },
  { value: 'Œ', description: 'uppercase ligature oe', number: 140, code: '&#140;', friendlyCode: '', unicode: 0x152 },
  { value: 'Ž', description: 'latin capital letter z with caron', number: 142, code: '&#142;', friendlyCode: '', unicode: 0x17d },
  { value: '‘', description: 'opening single quotation mark', number: 145, code: '&#145;', friendlyCode: '', unicode: 0x2018 },
  { value: '’', description: 'closing single quotation mark', number: 146, code: '&#146;', friendlyCode: '', unicode: 0x2019 },
  { value: '“', description: 'opening double quotation mark', number: 147, code: '&#147;', friendlyCode: '', unicode: 0x201c },
  { value: '”', description: 'closing double quotation mark', number: 148, code: '&#148;', friendlyCode: '', unicode: 0x201d },
  { value: '•', description: 'bullet', number: 149, code: '&#149;', friendlyCode: '', unicode: 0x2022 },
  { value: '–', description: 'en dash', number: 150, code: '&#150;', friendlyCode: '', unicode: 0x2013 },
  { value: '—', description: 'em dash', number: 151, code: '&#151;', friendlyCode: '', unicode: 0x2014 },
  { value: '˜', description: 'tilde', number: 152, code: '&#152;', friendlyCode: '', unicode: 0x2dc },
  { value: '™', description: 'trademark', number: 153, code: '&#153;', friendlyCode: '', unicode: 0x2122 },
  { value: 'š', description: 'latin small letter s with caron', number: 154, code: '&#154;', friendlyCode: '', unicode: 0x161 },
  { value: '›', description: 'single right angle quotation', number: 155, code: '&#155;', friendlyCode: '', unicode: 0x203a },
  { value: 'œ', description: 'lowercase ligature oe', number: 156, code: '&#156;', friendlyCode: '', unicode: 0x153 },
  { value: 'ž', description: 'latin small letter z with caron', number: 158, code: '&#158;', friendlyCode: '', unicode: 0x17e },
  { value: 'Ÿ', description: 'latin capital letter y with diaeresis', number: 159, code: '&#159;', friendlyCode: '', unicode: 0x178 },
  { value: 'Non-breaking space', description: 'non-breaking space', number: 160, code: '&#160;', friendlyCode: '&#nbsp;', unicode: 0xa0 },
  { value: '¡', description: 'inverted exclamation mark', number: 161, code: '&#161;', friendlyCode: '&#iexcl;', unicode: 0xa1 },
  { value: '¢', description: 'cent', number: 162, code: '&#162;', friendlyCode: '&#cent;', unicode: 0xa2 },
  { value: '£', description: 'pound', number: 163, code: '&#163;', friendlyCode: '&#pound;', unicode: 0xa3 },
  { value: '¤', description: 'currency', number: 164, code: '&#164;', friendlyCode: '&#curren;', unicode: 0xa4 },
  { value: '¥', description: 'yen', number: 165, code: '&#165;', friendlyCode: '&#yen;', unicode: 0xa5 },
  { value: '¦', description: 'broken vertical bar', number: 166, code: '&#166;', friendlyCode: '&#brvbar;', unicode: 0xa6 },
  { value: '§', description: 'section', number: 167, code: '&#167;', friendlyCode: '&#sect;', unicode: 0xa7 },
  { value: '¨', description: 'spacing diaeresis', number: 168, code: '&#168;', friendlyCode: '&#uml;', unicode: 0xa8 },
  { value: '©', description: 'copyright', number: 169, code: '&#169;', friendlyCode: '&#copy;', unicode: 0xa9 },
  { value: 'ª', description: 'feminine ordinal indicator', number: 170, code: '&#170;', friendlyCode: '&#ordf;', unicode: 0xaa },
  { value: '«', description: 'opening/left angle quotation mark', number: 171, code: '&#171;', friendlyCode: '&#laquo;', unicode: 0xab },
  { value: '¬', description: 'negation', number: 172, code: '&#172;', friendlyCode: '&#not;', unicode: 0xac },
  { value: '­', description: 'soft hyphen', number: 173, code: '&#173;', friendlyCode: '&#shy;', unicode: 0xad },
  { value: '®', description: 'registered trademark', number: 174, code: '&#174;', friendlyCode: '&#reg;', unicode: 0xae },
  { value: '¯', description: 'spacing macron', number: 175, code: '&#175;', friendlyCode: '&#macr;', unicode: 0xaf },
  { value: '°', description: 'degree', number: 176, code: '&#176;', friendlyCode: '&#deg;', unicode: 0xb0 },
  { value: '±', description: 'plus or minus', number: 177, code: '&#177;', friendlyCode: '&#plusmn;', unicode: 0xb1 },
  { value: '²', description: 'superscript 2', number: 178, code: '&#178;', friendlyCode: '&#sup2;', unicode: 0xb2 },
  { value: '³', description: 'superscript 3', number: 179, code: '&#179;', friendlyCode: '&#sup3;', unicode: 0xb3 },
  { value: '´', description: 'spacing acute', number: 180, code: '&#180;', friendlyCode: '&#acute;', unicode: 0xb4 },
  { value: 'µ', description: 'micro', number: 181, code: '&#181;', friendlyCode: '&#micro;', unicode: 0xb5 },
  { value: '¶', description: 'paragraph', number: 182, code: '&#182;', friendlyCode: '&#para;', unicode: 0xb6 },
  { value: '·', description: 'dot', number: 182, code: '&#183;', friendlyCode: '&#dot;', unicode: 0xb7 },
  { value: '¸', description: 'spacing cedilla', number: 184, code: '&#184;', friendlyCode: '&#cedil;', unicode: 0xb8 },
  { value: '¹', description: 'superscript 1', number: 185, code: '&#185;', friendlyCode: '&#sup1;', unicode: 0xb9 },
  { value: 'º', description: 'masculine ordinal indicator', number: 186, code: '&#186;', friendlyCode: '&#ordm;', unicode: 0xba },
  { value: '»', description: 'closing/right angle quotation mark', number: 187, code: '&#187;', friendlyCode: '&#raquo;', unicode: 0xbb },
  { value: '¼', description: 'fraction 1/4', number: 188, code: '&#188;', friendlyCode: '&#frac14;', unicode: 0xbc },
  { value: '½', description: 'fraction 1/2', number: 189, code: '&#189;', friendlyCode: '&#frac12;', unicode: 0xbd },
  { value: '¾', description: 'fraction 3/4', number: 190, code: '&#190;', friendlyCode: '&#frac34;', unicode: 0xbe },
  { value: '¿', description: 'inverted question mark', number: 191, code: '&#191;', friendlyCode: '&#iquest;', unicode: 0xbf },
  { value: 'À', description: 'capital a with grave accent', number: 192, code: '&#192;', friendlyCode: '&#agrave;', unicode: 0xc0 },
  { value: 'Á', description: 'capital a with acute accent', number: 193, code: '&#193;', friendlyCode: '&#aacute;', unicode: 0xc1 },
  { value: 'Â', description: 'capital a with circumflex accent', number: 194, code: '&#194;', friendlyCode: '&#acirc;', unicode: 0xc2 },
  { value: 'Ã', description: 'capital a with tilde', number: 195, code: '&#195;', friendlyCode: '&#atilde;', unicode: 0xc3 },
  { value: 'Ä', description: 'capital a with umlaut', number: 196, code: '&#196;', friendlyCode: '&#auml;', unicode: 0xc4 },
  { value: 'Å', description: 'capital a with ring', number: 197, code: '&#197;', friendlyCode: '&#aring;', unicode: 0xc5 },
  { value: 'Æ', description: 'capital ae', number: 198, code: '&#198;', friendlyCode: '&#aelig;', unicode: 0xc6 },
  { value: 'Ç', description: 'capital c with cedilla', number: 199, code: '&#199;', friendlyCode: '&#ccedil;', unicode: 0xc7 },
  { value: 'È', description: 'capital e with grave accent', number: 200, code: '&#200;', friendlyCode: '&#egrave;', unicode: 0xc8 },
  { value: 'É', description: 'capital e with acute accent', number: 201, code: '&#201;', friendlyCode: '&#eacute;', unicode: 0xc9 },
  { value: 'Ê', description: 'capital e with circumflex accent', number: 202, code: '&#202;', friendlyCode: '&#ecirc;', unicode: 0xca },
  { value: 'Ë', description: 'capital e with umlaut', number: 203, code: '&#203;', friendlyCode: '&#euml;', unicode: 0xcb },
  { value: 'Ì', description: 'capital i with grave accent', number: 204, code: '&#204;', friendlyCode: '&#igrave;', unicode: 0xcc },
  { value: 'Í', description: 'capital i with accute accent', number: 205, code: '&#205;', friendlyCode: '&#iacute;', unicode: 0xcd },
  { value: 'Î', description: 'capital i with circumflex accent', number: 206, code: '&#206;', friendlyCode: '&#icirc;', unicode: 0xce },
  { value: 'Ï', description: 'capital i with umlaut', number: 207, code: '&#207;', friendlyCode: '&#iuml;', unicode: 0xcf },
  { value: 'Ð', description: 'capital eth (icelandic)', number: 208, code: '&#208;', friendlyCode: '&#eth;', unicode: 0xd0 },
  { value: 'Ñ', description: 'capital n with tilde', number: 209, code: '&#209;', friendlyCode: '&#ntilde;', unicode: 0xd1 },
  { value: 'Ò', description: 'capital o with grave accent', number: 210, code: '&#210;', friendlyCode: '&#ograve;', unicode: 0xd2 },
  { value: 'Ó', description: 'capital o with accute accent', number: 211, code: '&#211;', friendlyCode: '&#oacute;', unicode: 0xd3 },
  { value: 'Ô', description: 'capital o with circumflex accent', number: 212, code: '&#212;', friendlyCode: '&#ocirc;', unicode: 0xd4 },
  { value: 'Õ', description: 'capital o with tilde', number: 213, code: '&#213;', friendlyCode: '&#otilde;', unicode: 0xd5 },
  { value: 'Ö', description: 'capital o with umlaut', number: 214, code: '&#214;', friendlyCode: '&#ouml;', unicode: 0xd6 },
  { value: '×', description: 'multiplication', number: 215, code: '&#215;', friendlyCode: '&#times;', unicode: 0xd7 },
  { value: 'Ø', description: 'capital o with slash', number: 216, code: '&#216;', friendlyCode: '&#oslash;', unicode: 0xd8 },
  { value: 'Ù', description: 'capital u with grave accent', number: 217, code: '&#217;', friendlyCode: '&#ugrave;', unicode: 0xd9 },
  { value: 'Ú', description: 'capital u with acute accent', number: 218, code: '&#218;', friendlyCode: '&#uacute;', unicode: 0xda },
  { value: 'Û', description: 'capital u with circumflex accent', number: 219, code: '&#219;', friendlyCode: '&#ucirc;', unicode: 0xdb },
  { value: 'Ü', description: 'capital u with umlaut', number: 220, code: '&#220;', friendlyCode: '&#uuml;', unicode: 0xdc },
  { value: 'Ý', description: 'capital y with acute accent', number: 221, code: '&#221;', friendlyCode: '&#yacute;', unicode: 0xdd },
  { value: 'Þ', description: 'capital thorn (icelandic)', number: 222, code: '&#222;', friendlyCode: '&#thorn;', unicode: 0xde },
  { value: 'ß', description: 'lowercase sharp s (german)', number: 223, code: '&#223;', friendlyCode: '&#szlig;', unicode: 0xdf },
  { value: 'à', description: 'lowercase a with grave accent', number: 224, code: '&#224;', friendlyCode: '&#agrave;', unicode: 0xe0 },
  { value: 'á', description: 'lowercase a with acute accent', number: 225, code: '&#225;', friendlyCode: '&#aacute;', unicode: 0xe1 },
  { value: 'â', description: 'lowercase a with circumflex accent', number: 226, code: '&#226;', friendlyCode: '&#acirc;', unicode: 0xe2 },
  { value: 'ã', description: 'lowercase a with tilde', number: 227, code: '&#227;', friendlyCode: '&#atilde;', unicode: 0xe3 },
  { value: 'ä', description: 'lowercase a with umlaut', number: 228, code: '&#228;', friendlyCode: '&#auml;', unicode: 0xe4 },
  { value: 'å', description: 'lowercase a with ring', number: 229, code: '&#229;', friendlyCode: '&#aring;', unicode: 0xe5 },
  { value: 'æ', description: 'lowercase ae', number: 230, code: '&#230;', friendlyCode: '&#aelig;', unicode: 0xe6 },
  { value: 'ç', description: 'lowercase c with cedilla', number: 231, code: '&#231;', friendlyCode: '&#ccedil;', unicode: 0xe7 },
  { value: 'è', description: 'lowercase e with grave accent', number: 232, code: '&#232;', friendlyCode: '&#egrave;', unicode: 0xe8 },
  { value: 'é', description: 'lowercase e with acute accent', number: 233, code: '&#233;', friendlyCode: '&#eacute;', unicode: 0xe9 },
  { value: 'ê', description: 'lowercase e with circumflex accent', number: 234, code: '&#234;', friendlyCode: '&#ecirc;', unicode: 0xea },
  { value: 'ë', description: 'lowercase e with umlaut', number: 235, code: '&#235;', friendlyCode: '&#euml;', unicode: 0xeb },
  { value: 'ì', description: 'lowercase i with grave accent', number: 236, code: '&#236;', friendlyCode: '&#igrave;', unicode: 0xec },
  { value: 'í', description: 'lowercase i with acute accent', number: 237, code: '&#237;', friendlyCode: '&#iacute;', unicode: 0xed },
  { value: 'î', description: 'lowercase i with circumflex accent', number: 238, code: '&#238;', friendlyCode: '&#icirc;', unicode: 0xee },
  { value: 'ï', description: 'lowercase i with umlaut', number: 239, code: '&#239;', friendlyCode: '&#iuml;', unicode: 0xef },
  { value: 'ð', description: 'lowercase eth (icelandic)', number: 240, code: '&#240;', friendlyCode: '&#eth;', unicode: 0xf0 },
  { value: 'ñ', description: 'lowercase n with tilde', number: 241, code: '&#241;', friendlyCode: '&#ntilde;', unicode: 0xf1 },
  { value: 'ò', description: 'lowercase o with grave accent', number: 242, code: '&#242;', friendlyCode: '&#ograve;', unicode: 0xf2 },
  { value: 'ó', description: 'lowercase o with acute accent', number: 243, code: '&#243;', friendlyCode: '&#oacute;', unicode: 0xf3 },
  { value: 'ô', description: 'lowercase o with circumflex accent', number: 244, code: '&#244;', friendlyCode: '&#ocirc;', unicode: 0xf4 },
  { value: 'õ', description: 'lowercase o with tilde', number: 245, code: '&#245;', friendlyCode: '&#otilde;', unicode: 0xf5 },
  { value: 'ö', description: 'lowercase o with umlaut', number: 246, code: '&#246;', friendlyCode: '&#ouml;', unicode: 0xf6 },
  { value: '÷', description: 'divide', number: 247, code: '&#247;', friendlyCode: '&#divide;', unicode: 0xf7 },
  { value: 'ø', description: 'lowercase o with slash', number: 248, code: '&#248;', friendlyCode: '&#oslash;', unicode: 0xf8 },
  { value: 'ù', description: 'lowercase u with grave accent', number: 249, code: '&#249;', friendlyCode: '&#ugrave;', unicode: 0xf9 },
  { value: 'ú', description: 'lowercase u with acute accent', number: 250, code: '&#250;', friendlyCode: '&#uacute;', unicode: 0xfa },
  { value: 'û', description: 'lowercase u with circumflex accent', number: 251, code: '&#251;', friendlyCode: '&#ucirc;', unicode: 0xfb },
  { value: 'ü', description: 'lowercase u with umlaut', number: 252, code: '&#252;', friendlyCode: '&#uuml;', unicode: 0xfc },
  { value: 'ý', description: 'lowercase y with acute accent', number: 253, code: '&#253;', friendlyCode: '&#yacute;', unicode: 0xfd },
  { value: 'þ', description: 'lowercase thorn (icelandic)', number: 254, code: '&#254;', friendlyCode: '&#thorn;', unicode: 0xfe },
  { value: 'ÿ', description: 'lowercase y with umlaut', number: 255, code: '&#255;', friendlyCode: '&#yuml;', unicode: 0xff },
  { value: 'Ā', description: 'latin capital letter a with macron', number: 256, code: '&#256;', friendlyCode: '&#amacr;', unicode: 0x100 },
  { value: 'ā', description: 'latin small letter a with macron', number: 257, code: '&#257;', friendlyCode: '&#amacr;', unicode: 0x101 },
  { value: 'Ă', description: 'latin capital letter a with breve', number: 258, code: '&#258;', friendlyCode: '&#abreve;', unicode: 0x102 },
  { value: 'ă', description: 'latin small letter a with breve', number: 259, code: '&#259;', friendlyCode: '&#abreve;', unicode: 0x103 },
  { value: 'Ą', description: 'latin capital letter a with ogonek', number: 260, code: '&#260;', friendlyCode: '&#aogon;', unicode: 0x104 },
  { value: 'ą', description: 'latin small letter a with ogonek', number: 261, code: '&#261;', friendlyCode: '&#aogon;', unicode: 0x105 },
  { value: 'Ć', description: 'latin capital letter c with acute', number: 262, code: '&#262;', friendlyCode: '&#cacute;', unicode: 0x106 },
  { value: 'ć', description: 'latin small letter c with acute', number: 263, code: '&#263;', friendlyCode: '&#cacute;', unicode: 0x107 },
  { value: 'Ĉ', description: 'latin capital letter c with circumflex', number: 264, code: '&#264;', friendlyCode: '&#ccirc;', unicode: 0x108 },
  { value: 'ĉ', description: 'latin small letter c with circumflex', number: 265, code: '&#265;', friendlyCode: '&#ccirc;', unicode: 0x109 },
  { value: 'Ċ', description: 'latin capital letter c with dot above', number: 266, code: '&#266;', friendlyCode: '&#cdot;', unicode: 0x10a },
  { value: 'ċ', description: 'latin small letter c with dot above', number: 267, code: '&#267;', friendlyCode: '&#cdot;', unicode: 0x10b },
  { value: 'Č', description: 'latin capital letter c with caron', number: 268, code: '&#268;', friendlyCode: '&#ccaron;', unicode: 0x10c },
  { value: 'č', description: 'latin small letter c with caron', number: 269, code: '&#269;', friendlyCode: '&#ccaron;', unicode: 0x10d },
  { value: 'Ď', description: 'latin capital letter d with caron', number: 270, code: '&#270;', friendlyCode: '&#dcaron;', unicode: 0x10e },
  { value: 'ď', description: 'latin small letter d with caron', number: 271, code: '&#271;', friendlyCode: '&#dcaron;', unicode: 0x10f },
  { value: 'Đ', description: 'latin capital letter d with stroke', number: 272, code: '&#272;', friendlyCode: '&#dstrok;', unicode: 0x110 },
  { value: 'đ', description: 'latin small letter d with stroke', number: 273, code: '&#273;', friendlyCode: '&#dstrok;', unicode: 0x111 },
  { value: 'Ē', description: 'latin capital letter e with macron', number: 274, code: '&#274;', friendlyCode: '&#emacr;', unicode: 0x112 },
  { value: 'ē', description: 'latin small letter e with macron', number: 275, code: '&#275;', friendlyCode: '&#emacr;', unicode: 0x113 },
  { value: 'Ĕ', description: 'latin capital letter e with breve', number: 276, code: '&#276;', friendlyCode: '&#ebreve;', unicode: 0x114 },
  { value: 'ĕ', description: 'latin small letter e with breve', number: 277, code: '&#277;', friendlyCode: '&#ebreve;', unicode: 0x115 },
  { value: 'Ė', description: 'latin capital letter e with dot above', number: 278, code: '&#278;', friendlyCode: '&#edot;', unicode: 0x116 },
  { value: 'ė', description: 'latin small letter e with dot above', number: 279, code: '&#279;', friendlyCode: '&#edot;', unicode: 0x117 },
  { value: 'Ę', description: 'latin capital letter e with ogonek', number: 280, code: '&#280;', friendlyCode: '&#eogon;', unicode: 0x118 },
  { value: 'ę', description: 'latin small letter e with ogonek', number: 281, code: '&#281;', friendlyCode: '&#eogon;', unicode: 0x119 },
  { value: 'Ě', description: 'latin capital letter e with caron', number: 282, code: '&#282;', friendlyCode: '&#ecaron;', unicode: 0x11a },
  { value: 'ě', description: 'latin small letter e with caron', number: 283, code: '&#283;', friendlyCode: '&#ecaron;', unicode: 0x11b },
  { value: 'Ĝ', description: 'latin capital letter g with circumflex', number: 284, code: '&#284;', friendlyCode: '&#gcirc;', unicode: 0x11c },
  { value: 'ĝ', description: 'latin small letter g with circumflex', number: 285, code: '&#285;', friendlyCode: '&#gcirc;', unicode: 0x11d },
  { value: 'Ğ', description: 'latin capital letter g with breve', number: 286, code: '&#286;', friendlyCode: '&#gbreve;', unicode: 0x11e },
  { value: 'ğ', description: 'latin small letter g with breve', number: 287, code: '&#287;', friendlyCode: '&#gbreve;', unicode: 0x11f },
  { value: 'Ġ', description: 'latin capital letter g with dot above', number: 288, code: '&#288;', friendlyCode: '&#gdot;', unicode: 0x120 },
  { value: 'ġ', description: 'latin small letter g with dot above', number: 289, code: '&#289;', friendlyCode: '&#gdot;', unicode: 0x121 },
  { value: 'Ģ', description: 'latin capital letter g with cedilla', number: 290, code: '&#290;', friendlyCode: '&#gcedil;', unicode: 0x122 },
  { value: 'ģ', description: 'latin small letter g with cedilla', number: 291, code: '&#291;', friendlyCode: '&#gcedil;', unicode: 0x123 },
  { value: 'Ĥ', description: 'latin capital letter h with circumflex', number: 292, code: '&#292;', friendlyCode: '&#hcirc;', unicode: 0x124 },
  { value: 'ĥ', description: 'latin small letter h with circumflex', number: 293, code: '&#293;', friendlyCode: '&#hcirc;', unicode: 0x125 },
  { value: 'Ħ', description: 'latin capital letter h with stroke', number: 294, code: '&#294;', friendlyCode: '&#hstrok;', unicode: 0x126 },
  { value: 'ħ', description: 'latin small letter h with stroke', number: 295, code: '&#295;', friendlyCode: '&#hstrok;', unicode: 0x127 },
  { value: 'Ĩ', description: 'latin capital letter i with tilde', number: 296, code: '&#296;', friendlyCode: '&#itilde;', unicode: 0x128 },
  { value: 'ĩ', description: 'latin small letter i with tilde', number: 297, code: '&#297;', friendlyCode: '&#itilde;', unicode: 0x129 },
  { value: 'Ī', description: 'latin capital letter i with macron', number: 298, code: '&#298;', friendlyCode: '&#imacr;', unicode: 0x12a },
  { value: 'ī', description: 'latin small letter i with macron', number: 299, code: '&#299;', friendlyCode: '&#imacr;', unicode: 0x12b },
  { value: 'Ĭ', description: 'latin capital letter i with breve', number: 300, code: '&#300;', friendlyCode: '&#ibreve;', unicode: 0x12c },
  { value: 'ĭ', description: 'latin small letter i with breve', number: 301, code: '&#301;', friendlyCode: '&#ibreve;', unicode: 0x12d },
  { value: 'Į', description: 'latin capital letter i with ogonek', number: 302, code: '&#302;', friendlyCode: '&#iogon;', unicode: 0x12e },
  { value: 'į', description: 'latin small letter i with ogonek', number: 303, code: '&#303;', friendlyCode: '&#iogon;', unicode: 0x12f },
  { value: 'İ', description: 'latin capital letter i with dot above', number: 304, code: '&#304;', friendlyCode: '&#idot;', unicode: 0x130 },
  { value: 'ı', description: 'latin small letter dotless i', number: 305, code: '&#305;', friendlyCode: '&#imath; &inodot;', unicode: 0x131 },
  { value: 'Ĳ', description: 'latin capital ligature ij', number: 306, code: '&#306;', friendlyCode: '&#ijlig;', unicode: 0x132 },
  { value: 'ĳ', description: 'latin small ligature ij', number: 307, code: '&#307;', friendlyCode: '&#ijlig;', unicode: 0x133 },
  { value: 'Ĵ', description: 'latin capital letter j with circumflex', number: 308, code: '&#308;', friendlyCode: '&#jcirc;', unicode: 0x134 },
  { value: 'ĵ', description: 'latin small letter j with circumflex', number: 309, code: '&#309;', friendlyCode: '&#jcirc;', unicode: 0x135 },
  { value: 'Ķ', description: 'latin capital letter k with cedilla', number: 310, code: '&#310;', friendlyCode: '&#kcedil;', unicode: 0x136 },
  { value: 'ķ', description: 'latin small letter k with cedilla', number: 311, code: '&#311;', friendlyCode: '&#kcedil;', unicode: 0x137 },
  { value: 'ĸ', description: 'latin small letter kra', number: 312, code: '&#312;', friendlyCode: '&#kgreen;', unicode: 0x138 },
  { value: 'Ĺ', description: 'latin capital letter l with acute', number: 313, code: '&#313;', friendlyCode: '&#lacute;', unicode: 0x139 },
  { value: 'ĺ', description: 'latin small letter l with acute', number: 314, code: '&#314;', friendlyCode: '&#lacute;', unicode: 0x13a },
  { value: 'Ļ', description: 'latin capital letter l with cedilla', number: 315, code: '&#315;', friendlyCode: '&#lcedil;', unicode: 0x13b },
  { value: 'ļ', description: 'latin small letter l with cedilla', number: 316, code: '&#316;', friendlyCode: '&#lcedil;', unicode: 0x13c },
  { value: 'Ľ', description: 'latin capital letter l with caron', number: 317, code: '&#317;', friendlyCode: '&#lcaron;', unicode: 0x13d },
  { value: 'ľ', description: 'latin small letter l with caron', number: 318, code: '&#318;', friendlyCode: '&#lcaron;', unicode: 0x13e },
  { value: 'Ŀ', description: 'latin capital letter l with middle dot', number: 319, code: '&#319;', friendlyCode: '&#lmidot;', unicode: 0x13f },
  { value: 'ŀ', description: 'latin small letter l with middle dot', number: 320, code: '&#320;', friendlyCode: '&#lmidot;', unicode: 0x140 },
  { value: 'Ł', description: 'latin capital letter l with stroke', number: 321, code: '&#321;', friendlyCode: '&#lstrok;', unicode: 0x141 },
  { value: 'ł', description: 'latin small letter l with stroke', number: 322, code: '&#322;', friendlyCode: '&#lstrok;', unicode: 0x142 },
  { value: 'Ń', description: 'latin capital letter n with acute', number: 323, code: '&#323;', friendlyCode: '&#nacute;', unicode: 0x143 },
  { value: 'ń', description: 'latin small letter n with acute', number: 324, code: '&#324;', friendlyCode: '&#nacute;', unicode: 0x144 },
  { value: 'Ņ', description: 'latin capital letter n with cedilla', number: 325, code: '&#325;', friendlyCode: '&#ncedil;', unicode: 0x145 },
  { value: 'ņ', description: 'latin small letter n with cedilla', number: 326, code: '&#326;', friendlyCode: '&#ncedil;', unicode: 0x146 },
  { value: 'Ň', description: 'latin capital letter n with caron', number: 327, code: '&#327;', friendlyCode: '&#ncaron;', unicode: 0x147 },
  { value: 'ň', description: 'latin small letter n with caron', number: 328, code: '&#328;', friendlyCode: '&#ncaron;', unicode: 0x148 },
  { value: 'ŉ', description: 'latin small letter n preceded by apostrophe', number: 329, code: '&#329;', friendlyCode: '&#napos;', unicode: 0x149 },
  { value: 'Ŋ', description: 'latin capital letter eng', number: 330, code: '&#330;', friendlyCode: '&#eng;', unicode: 0x14a },
  { value: 'ŋ', description: 'latin small letter eng', number: 331, code: '&#331;', friendlyCode: '&#eng;', unicode: 0x14b },
  { value: 'Ō', description: 'latin capital letter o with macron', number: 332, code: '&#332;', friendlyCode: '&#omacr;', unicode: 0x14c },
  { value: 'ō', description: 'latin small letter o with macron', number: 333, code: '&#333;', friendlyCode: '&#omacr;', unicode: 0x14d },
  { value: 'Ŏ', description: 'latin capital letter o with breve', number: 334, code: '&#334;', friendlyCode: '&#obreve;', unicode: 0x14e },
  { value: 'ŏ', description: 'latin small letter o with breve', number: 335, code: '&#335;', friendlyCode: '&#obreve;', unicode: 0x14f },
  { value: 'Ő', description: 'latin capital letter o with double acute', number: 336, code: '&#336;', friendlyCode: '&#odblac;', unicode: 0x150 },
  { value: 'ő', description: 'latin small letter o with double acute', number: 337, code: '&#337;', friendlyCode: '&#odblac;', unicode: 0x151 },
  { value: 'Œ', description: 'uppercase ligature oe', number: 338, code: '&#338;', friendlyCode: '&#oelig;', unicode: 0x152 },
  { value: 'œ', description: 'lowercase ligature oe', number: 339, code: '&#339;', friendlyCode: '&#oelig;', unicode: 0x153 },
  { value: 'Ŕ', description: 'latin capital letter r with acute', number: 340, code: '&#340;', friendlyCode: '&#racute;', unicode: 0x154 },
  { value: 'ŕ', description: 'latin small letter r with acute', number: 341, code: '&#341;', friendlyCode: '&#racute;', unicode: 0x155 },
  { value: 'Ŗ', description: 'latin capital letter r with cedilla', number: 342, code: '&#342;', friendlyCode: '&#rcedil;', unicode: 0x156 },
  { value: 'ŗ', description: 'latin small letter r with cedilla', number: 343, code: '&#343;', friendlyCode: '&#rcedil;', unicode: 0x157 },
  { value: 'Ř', description: 'latin capital letter r with caron', number: 344, code: '&#344;', friendlyCode: '&#rcaron;', unicode: 0x158 },
  { value: 'ř', description: 'latin small letter r with caron', number: 345, code: '&#345;', friendlyCode: '&#rcaron;', unicode: 0x159 },
  { value: 'Ś', description: 'latin capital letter s with acute', number: 346, code: '&#346;', friendlyCode: '&#sacute;', unicode: 0x15a },
  { value: 'ś', description: 'latin small letter s with acute', number: 347, code: '&#347;', friendlyCode: '&#sacute;', unicode: 0x15b },
  { value: 'Ŝ', description: 'latin capital letter s with circumflex', number: 348, code: '&#348;', friendlyCode: '&#scirc;', unicode: 0x15c },
  { value: 'ŝ', description: 'latin small letter s with circumflex', number: 349, code: '&#349;', friendlyCode: '&#scirc;', unicode: 0x15d },
  { value: 'Ş', description: 'latin capital letter s with cedilla', number: 350, code: '&#350;', friendlyCode: '&#scedil;', unicode: 0x15e },
  { value: 'ş', description: 'latin small letter s with cedilla', number: 351, code: '&#351;', friendlyCode: '&#scedil;', unicode: 0x15f },
  { value: 'Š', description: 'uppercase s with caron', number: 352, code: '&#352;', friendlyCode: '&#scaron;', unicode: 0x160 },
  { value: 'š', description: 'lowercase s with caron', number: 353, code: '&#353;', friendlyCode: '&#scaron;', unicode: 0x161 },
  { value: 'Ţ', description: 'latin capital letter t with cedilla', number: 354, code: '&#354;', friendlyCode: '&#tcedil;', unicode: 0x162 },
  { value: 'ţ', description: 'latin small letter t with cedilla', number: 355, code: '&#355;', friendlyCode: '&#tcedil;', unicode: 0x163 },
  { value: 'Ť', description: 'latin capital letter t with caron', number: 356, code: '&#356;', friendlyCode: '&#tcaron;', unicode: 0x164 },
  { value: 'ť', description: 'latin small letter t with caron', number: 357, code: '&#357;', friendlyCode: '&#tcaron;', unicode: 0x165 },
  { value: 'Ŧ', description: 'latin capital letter t with stroke', number: 358, code: '&#358;', friendlyCode: '&#tstrok;', unicode: 0x166 },
  { value: 'ŧ', description: 'latin small letter t with stroke', number: 359, code: '&#359;', friendlyCode: '&#tstrok;', unicode: 0x167 },
  { value: 'Ũ', description: 'latin capital letter u with tilde', number: 360, code: '&#360;', friendlyCode: '&#utilde;', unicode: 0x168 },
  { value: 'ũ', description: 'latin small letter u with tilde', number: 361, code: '&#361;', friendlyCode: '&#utilde;', unicode: 0x169 },
  { value: 'Ū', description: 'latin capital letter u with macron', number: 362, code: '&#362;', friendlyCode: '&#umacr;', unicode: 0x16a },
  { value: 'ū', description: 'latin small letter u with macron', number: 363, code: '&#363;', friendlyCode: '&#umacr;', unicode: 0x16b },
  { value: 'Ŭ', description: 'latin capital letter u with breve', number: 364, code: '&#364;', friendlyCode: '&#ubreve;', unicode: 0x16c },
  { value: 'ŭ', description: 'latin small letter u with breve', number: 365, code: '&#365;', friendlyCode: '&#ubreve;', unicode: 0x16d },
  { value: 'Ů', description: 'latin capital letter u with ring above', number: 366, code: '&#366;', friendlyCode: '&#uring;', unicode: 0x16e },
  { value: 'ů', description: 'latin small letter u with ring above', number: 367, code: '&#367;', friendlyCode: '&#uring;', unicode: 0x16f },
  { value: 'Ű', description: 'latin capital letter u with double acute', number: 368, code: '&#368;', friendlyCode: '&#udblac;', unicode: 0x170 },
  { value: 'ű', description: 'latin small letter u with double acute', number: 369, code: '&#369;', friendlyCode: '&#udblac;', unicode: 0x171 },
  { value: 'Ų', description: 'latin capital letter u with ogonek', number: 370, code: '&#370;', friendlyCode: '&#uogon;', unicode: 0x172 },
  { value: 'ų', description: 'latin small letter u with ogonek', number: 371, code: '&#371;', friendlyCode: '&#uogon;', unicode: 0x173 },
  { value: 'Ŵ', description: 'latin capital letter w with circumflex', number: 372, code: '&#372;', friendlyCode: '&#wcirc;', unicode: 0x174 },
  { value: 'ŵ', description: 'latin small letter w with circumflex', number: 373, code: '&#373;', friendlyCode: '&#wcirc;', unicode: 0x175 },
  { value: 'Ŷ', description: 'latin capital letter y with circumflex', number: 374, code: '&#374;', friendlyCode: '&#ycirc;', unicode: 0x176 },
  { value: 'ŷ', description: 'latin small letter y with circumflex', number: 375, code: '&#375;', friendlyCode: '&#ycirc;', unicode: 0x177 },
  { value: 'Ÿ', description: 'capital y with diaeres', number: 376, code: '&#376;', friendlyCode: '&#yuml;', unicode: 0x178 },
  { value: 'ƒ', description: 'lowercase with hook', number: 402, code: '&#402;', friendlyCode: '&#fnof;', unicode: 0x192 },
  { value: 'ˆ', description: 'circumflex accent', number: 710, code: '&#710;', friendlyCode: '&#circ;', unicode: 0x2c6 },
  { value: '˜', description: 'tilde', number: 732, code: '&#732;', friendlyCode: '&#tilde;', unicode: 0x2dc },
  { value: 'Α', description: 'alpha', number: 913, code: '&#913;', friendlyCode: '&#alpha;', unicode: 0x391 },
  { value: 'Β', description: 'beta', number: 914, code: '&#914;', friendlyCode: '&#beta;', unicode: 0x392 },
  { value: 'Γ', description: 'gamma', number: 915, code: '&#915;', friendlyCode: '&#gamma;', unicode: 0x393 },
  { value: 'Δ', description: 'delta', number: 916, code: '&#916;', friendlyCode: '&#delta;', unicode: 0x394 },
  { value: 'Ε', description: 'epsilon', number: 917, code: '&#917;', friendlyCode: '&#epsilon;', unicode: 0x395 },
  { value: 'Ζ', description: 'zeta', number: 918, code: '&#918;', friendlyCode: '&#zeta;', unicode: 0x396 },
  { value: 'Η', description: 'eta', number: 919, code: '&#919;', friendlyCode: '&#eta;', unicode: 0x397 },
  { value: 'Θ', description: 'theta', number: 920, code: '&#920;', friendlyCode: '&#theta;', unicode: 0x398 },
  { value: 'Ι', description: 'iota', number: 921, code: '&#921;', friendlyCode: '&#iota;', unicode: 0x399 },
  { value: 'Κ', description: 'kappa', number: 922, code: '&#922;', friendlyCode: '&#kappa;', unicode: 0x39a },
  { value: 'Λ', description: 'lambda', number: 923, code: '&#923;', friendlyCode: '&#lambda;', unicode: 0x39b },
  { value: 'Μ', description: 'mu', number: 924, code: '&#924;', friendlyCode: '&#mu;', unicode: 0x39c },
  { value: 'Ν', description: 'nu', number: 925, code: '&#925;', friendlyCode: '&#nu;', unicode: 0x39d },
  { value: 'Ξ', description: 'xi', number: 926, code: '&#926;', friendlyCode: '&#xi;', unicode: 0x39e },
  { value: 'Ο', description: 'omicron', number: 927, code: '&#927;', friendlyCode: '&#omicron;', unicode: 0x39f },
  { value: 'Π', description: 'pi', number: 928, code: '&#928;', friendlyCode: '&#pi;', unicode: 0x3a0 },
  { value: 'Ρ', description: 'rho', number: 929, code: '&#929;', friendlyCode: '&#rho;', unicode: 0x3a1 },
  { value: 'Σ', description: 'sigma', number: 931, code: '&#931;', friendlyCode: '&#sigma;', unicode: 0x3a3 },
  { value: 'Τ', description: 'tau', number: 932, code: '&#932;', friendlyCode: '&#tau;', unicode: 0x3a4 },
  { value: 'Υ', description: 'upsilon', number: 933, code: '&#933;', friendlyCode: '&#upsilon;', unicode: 0x3a5 },
  { value: 'Φ', description: 'phi', number: 934, code: '&#934;', friendlyCode: '&#phi;', unicode: 0x3a6 },
  { value: 'Χ', description: 'chi', number: 935, code: '&#935;', friendlyCode: '&#chi;', unicode: 0x3a7 },
  { value: 'Ψ', description: 'psi', number: 936, code: '&#936;', friendlyCode: '&#psi;', unicode: 0x3a8 },
  { value: 'Ω', description: 'omega', number: 937, code: '&#937;', friendlyCode: '&#omega;', unicode: 0x3a9 },
  { value: 'α', description: 'alpha', number: 945, code: '&#945;', friendlyCode: '&#alpha;', unicode: 0x3b1 },
  { value: 'β', description: 'beta', number: 946, code: '&#946;', friendlyCode: '&#beta;', unicode: 0x3b2 },
  { value: 'γ', description: 'gamma', number: 947, code: '&#947;', friendlyCode: '&#gamma;', unicode: 0x3b3 },
  { value: 'δ', description: 'delta', number: 948, code: '&#948;', friendlyCode: '&#delta;', unicode: 0x3b4 },
  { value: 'ε', description: 'epsilon', number: 949, code: '&#949;', friendlyCode: '&#epsilon;', unicode: 0x3b5 },
  { value: 'ζ', description: 'zeta', number: 950, code: '&#950;', friendlyCode: '&#zeta;', unicode: 0x3b6 },
  { value: 'η', description: 'eta', number: 951, code: '&#951;', friendlyCode: '&#eta;', unicode: 0x3b7 },
  { value: 'θ', description: 'theta', number: 952, code: '&#952;', friendlyCode: '&#theta;', unicode: 0x3b8 },
  { value: 'ι', description: 'iota', number: 953, code: '&#953;', friendlyCode: '&#iota;', unicode: 0x3b9 },
  { value: 'κ', description: 'kappa', number: 954, code: '&#954;', friendlyCode: '&#kappa;', unicode: 0x3ba },
  { value: 'λ', description: 'lambda', number: 955, code: '&#955;', friendlyCode: '&#lambda;', unicode: 0x3bb },
  { value: 'μ', description: 'mu', number: 956, code: '&#956;', friendlyCode: '&#mu;', unicode: 0x3bc },
  { value: 'ν', description: 'nu', number: 957, code: '&#957;', friendlyCode: '&#nu;', unicode: 0x3bd },
  { value: 'ξ', description: 'xi', number: 958, code: '&#958;', friendlyCode: '&#xi;', unicode: 0x3be },
  { value: 'ο', description: 'omicron', number: 959, code: '&#959;', friendlyCode: '&#omicron;', unicode: 0x3bf },
  { value: 'π', description: 'pi', number: 960, code: '&#960;', friendlyCode: '&#pi;', unicode: 0x3c0 },
  { value: 'ρ', description: 'rho', number: 961, code: '&#961;', friendlyCode: '&#rho;', unicode: 0x3c1 },
  { value: 'ς', description: 'sigmaf', number: 962, code: '&#962;', friendlyCode: '&#sigmaf;', unicode: 0x3c2 },
  { value: 'σ', description: 'sigma', number: 963, code: '&#963;', friendlyCode: '&#sigma;', unicode: 0x3c3 },
  { value: 'τ', description: 'tau', number: 964, code: '&#964;', friendlyCode: '&#tau;', unicode: 0x3c4 },
  { value: 'υ', description: 'upsilon', number: 965, code: '&#965;', friendlyCode: '&#upsilon;', unicode: 0x3c5 },
  { value: 'φ', description: 'phi', number: 966, code: '&#966;', friendlyCode: '&#phi;', unicode: 0x3c6 },
  { value: 'χ', description: 'chi', number: 967, code: '&#967;', friendlyCode: '&#chi;', unicode: 0x3c7 },
  { value: 'ψ', description: 'psi', number: 968, code: '&#968;', friendlyCode: '&#psi;', unicode: 0x3c8 },
  { value: 'ω', description: 'omega', number: 969, code: '&#969;', friendlyCode: '&#omega;', unicode: 0x3c9 },
  { value: 'ϑ', description: 'theta symbol', number: 977, code: '&#977;', friendlyCode: '&#thetasym;', unicode: 0x3d1 },
  { value: 'ϒ', description: 'upsilon symbol', number: 978, code: '&#978;', friendlyCode: '&#upsih;', unicode: 0x3d2 },
  { value: 'ϖ', description: 'pi symbol', number: 982, code: '&#982;', friendlyCode: '&#piv;', unicode: 0x3d6 },
  { value: 'En space', description: 'en space', number: 8194, code: '&#8194;', friendlyCode: '&#ensp;', unicode: 0 },
  { value: 'Em space', description: 'em space', number: 8195, code: '&#8195;', friendlyCode: '&#emsp;', unicode: 0 },
  { value: 'Thin space', description: 'thin space', number: 8201, code: '&#8201;', friendlyCode: '&#thinsp;', unicode: 0 },
  { value: 'Zero width non-joiner', description: 'zero width non-joiner', number: 8204, code: '&#8204;', friendlyCode: '&#zwnj;', unicode: 0 },
  { value: 'Zero width joiner', description: 'zero width joiner', number: 8205, code: '&#8205;', friendlyCode: '&#zwj;', unicode: 0 },
  { value: 'Left-to-right mark', description: 'left-to-right mark', number: 8206, code: '&#8206;', friendlyCode: '&#lrm;', unicode: 0 },
  { value: 'Right-to-left mark', description: 'right-to-left mark', number: 8207, code: '&#8207;', friendlyCode: '&#rlm;', unicode: 0 },
  { value: '–', description: 'en dash', number: 8211, code: '&#8211;', friendlyCode: '&#ndash;', unicode: 0x2013 },
  { value: '—', description: 'em dash', number: 8212, code: '&#8212;', friendlyCode: '&#mdash;', unicode: 0x2014 },
  { value: '‘', description: 'left single quotation mark', number: 8216, code: '&#8216;', friendlyCode: '&#lsquo;', unicode: 0x2018 },
  { value: '’', description: 'right single quotation mark', number: 8217, code: '&#8217;', friendlyCode: '&#rsquo;', unicode: 0x2019 },
  { value: '‚', description: 'single low-9 quotation mark', number: 8218, code: '&#8218;', friendlyCode: '&#sbquo;', unicode: 0x201a },
  { value: '“', description: 'left double quotation mark', number: 8220, code: '&#8220;', friendlyCode: '&#ldquo;', unicode: 0x201c },
  { value: '”', description: 'right double quotation mark', number: 8221, code: '&#8221;', friendlyCode: '&#rdquo;', unicode: 0x201d },
  { value: '„', description: 'double low-9 quotation mark', number: 8222, code: '&#8222;', friendlyCode: '&#bdquo;', unicode: 0x201e },
  { value: '†', description: 'dagger', number: 8224, code: '&#8224;', friendlyCode: '&#dagger;', unicode: 0x2020 },
  { value: '‡', description: 'double dagger', number: 8225, code: '&#8225;', friendlyCode: '&#dagger;', unicode: 0x2021 },
  { value: '•', description: 'bullet', number: 8226, code: '&#8226;', friendlyCode: '&#bull;', unicode: 0x2022 },
  { value: '…', description: 'horizontal ellipsis', number: 8230, code: '&#8230;', friendlyCode: '&#hellip;', unicode: 0x2026 },
  { value: '‰', description: 'per mille', number: 8240, code: '&#8240;', friendlyCode: '&#permil;', unicode: 0x2030 },
  { value: '′', description: 'minutes (degrees)', number: 8242, code: '&#8242;', friendlyCode: '&#prime;', unicode: 0x2032 },
  { value: '″', description: 'seconds (degrees)', number: 8243, code: '&#8243;', friendlyCode: '&#prime;', unicode: 0x2033 },
  { value: '‹', description: 'single left angle quotation', number: 8249, code: '&#8249;', friendlyCode: '&#lsaquo;', unicode: 0x2039 },
  { value: '›', description: 'single right angle quotation', number: 8250, code: '&#8250;', friendlyCode: '&#rsaquo;', unicode: 0x203a },
  { value: '‾', description: 'overline', number: 8254, code: '&#8254;', friendlyCode: '&#oline;', unicode: 0x203e },
  { value: '€', description: 'euro', number: 8364, code: '&#8364;', friendlyCode: '&#euro;', unicode: 0x20ac },
  { value: '™', description: 'trademark', number: 8482, code: '&#8482;', friendlyCode: '&#trade;', unicode: 0x2122 },
  { value: '←', description: 'left arrow', number: 8592, code: '&#8592;', friendlyCode: '&#larr;', unicode: 0x2190 },
  { value: '↑', description: 'up arrow', number: 8593, code: '&#8593;', friendlyCode: '&#uarr;', unicode: 0x2191 },
  { value: '→', description: 'right arrow', number: 8594, code: '&#8594;', friendlyCode: '&#rarr;', unicode: 0x2192 },
  { value: '↓', description: 'down arrow', number: 8595, code: '&#8595;', friendlyCode: '&#darr;', unicode: 0x2193 },
  { value: '↔', description: 'left right arrow', number: 8596, code: '&#8596;', friendlyCode: '&#harr;', unicode: 0x2194 },
  { value: '↵', description: 'carriage return arrow', number: 8629, code: '&#8629;', friendlyCode: '&#crarr;', unicode: 0x21b5 },
  { value: '∀', description: 'for all', number: 8704, code: '&#8704;', friendlyCode: '&#forall;', unicode: 0x2200 },
  { value: '∂', description: 'part', number: 8706, code: '&#8706;', friendlyCode: '&#part;', unicode: 0x2202 },
  { value: '∃', description: 'exist', number: 8707, code: '&#8707;', friendlyCode: '&#exist;', unicode: 0x2203 },
  { value: '∅', description: 'empty', number: 8709, code: '&#8709;', friendlyCode: '&#empty;', unicode: 0x2205 },
  { value: '∇', description: 'nabla', number: 8711, code: '&#8711;', friendlyCode: '&#nabla;', unicode: 0x2207 },
  { value: '∈', description: 'is in', number: 8712, code: '&#8712;', friendlyCode: '&#isin;', unicode: 0x2208 },
  { value: '∉', description: 'not in', number: 8713, code: '&#8713;', friendlyCode: '&#notin;', unicode: 0x2209 },
  { value: '∋', description: 'ni', number: 8715, code: '&#8715;', friendlyCode: '&#ni;', unicode: 0x220b },
  { value: '∏', description: 'product', number: 8719, code: '&#8719;', friendlyCode: '&#prod;', unicode: 0x220f },
  { value: '∑', description: 'sum', number: 8721, code: '&#8721;', friendlyCode: '&#sum;', unicode: 0x2211 },
  { value: '−', description: 'minus', number: 8722, code: '&#8722;', friendlyCode: '&#minus;', unicode: 0x2212 },
  { value: '∗', description: 'asterisk (lowast)', number: 8727, code: '&#8727;', friendlyCode: '&#lowast;', unicode: 0x2217 },
  { value: '√', description: 'square root', number: 8730, code: '&#8730;', friendlyCode: '&#radic;', unicode: 0x221a },
  { value: '∝', description: 'proportional to', number: 8733, code: '&#8733;', friendlyCode: '&#prop;', unicode: 0x221d },
  { value: '∞', description: 'infinity', number: 8734, code: '&#8734;', friendlyCode: '&#infin;', unicode: 0x221e },
  { value: '∠', description: 'angle', number: 8736, code: '&#8736;', friendlyCode: '&#ang;', unicode: 0x2220 },
  { value: '∧', description: 'and', number: 8743, code: '&#8743;', friendlyCode: '&#and;', unicode: 0x2227 },
  { value: '∨', description: 'or', number: 8744, code: '&#8744;', friendlyCode: '&#or;', unicode: 0x2228 },
  { value: '∩', description: 'cap', number: 8745, code: '&#8745;', friendlyCode: '&#cap;', unicode: 0x2229 },
  { value: '∪', description: 'cup', number: 8746, code: '&#8746;', friendlyCode: '&#cup;', unicode: 0x222a },
  { value: '∫', description: 'integral', number: 8747, code: '&#8747;', friendlyCode: '&#int;', unicode: 0x222b },
  { value: '∴', description: 'therefore', number: 8756, code: '&#8756;', friendlyCode: '&#there4;', unicode: 0x2234 },
  { value: '∼', description: 'similar to', number: 8764, code: '&#8764;', friendlyCode: '&#sim;', unicode: 0x223c },
  { value: '≅', description: 'congurent to', number: 8773, code: '&#8773;', friendlyCode: '&#cong;', unicode: 0x2245 },
  { value: '≈', description: 'almost equal', number: 8776, code: '&#8776;', friendlyCode: '&#asymp;', unicode: 0x2248 },
  { value: '≠', description: 'not equal', number: 8800, code: '&#8800;', friendlyCode: '&#ne;', unicode: 0x2260 },
  { value: '≡', description: 'equivalent', number: 8801, code: '&#8801;', friendlyCode: '&#equiv;', unicode: 0x2261 },
  { value: '≤', description: 'less or equal', number: 8804, code: '&#8804;', friendlyCode: '&#le;', unicode: 0x2264 },
  { value: '≥', description: 'greater or equal', number: 8805, code: '&#8805;', friendlyCode: '&#ge;', unicode: 0x2265 },
  { value: '⊂', description: 'subset of', number: 8834, code: '&#8834;', friendlyCode: '&#sub;', unicode: 0x2282 },
  { value: '⊃', description: 'superset of', number: 8835, code: '&#8835;', friendlyCode: '&#sup;', unicode: 0x2283 },
  { value: '⊄', description: 'not subset of', number: 8836, code: '&#8836;', friendlyCode: '&#nsub;', unicode: 0x2284 },
  { value: '⊆', description: 'subset or equal', number: 8838, code: '&#8838;', friendlyCode: '&#sube;', unicode: 0x2286 },
  { value: '⊇', description: 'superset or equal', number: 8839, code: '&#8839;', friendlyCode: '&#supe;', unicode: 0x2287 },
  { value: '⊕', description: 'circled plus', number: 8853, code: '&#8853;', friendlyCode: '&#oplus;', unicode: 0x2295 },
  { value: '⊗', description: 'circled times', number: 8855, code: '&#8855;', friendlyCode: '&#otimes;', unicode: 0x2297 },
  { value: '⊥', description: 'perpendicular', number: 8869, code: '&#8869;', friendlyCode: '&#perp;', unicode: 0x22a5 },
  { value: '⋅', description: 'dot operator', number: 8901, code: '&#8901;', friendlyCode: '&#sdot;', unicode: 0x22c5 },
  { value: '⌈', description: 'left ceiling', number: 8968, code: '&#8968;', friendlyCode: '&#lceil;', unicode: 0x2308 },
  { value: '⌉', description: 'right ceiling', number: 8969, code: '&#8969;', friendlyCode: '&#rceil;', unicode: 0x2309 },
  { value: '⌊', description: 'left floor', number: 8970, code: '&#8970;', friendlyCode: '&#lfloor;', unicode: 0x230a },
  { value: '⌋', description: 'right floor', number: 8971, code: '&#8971;', friendlyCode: '&#rfloor;', unicode: 0x230b },
  { value: '◊', description: 'lozenge', number: 9674, code: '&#9674;', friendlyCode: '&#loz;', unicode: 0x25ca },
  { value: '♠', description: 'spade', number: 9824, code: '&#9824;', friendlyCode: '&#spades;', unicode: 0x2660 },
  { value: '♣', description: 'club', number: 9827, code: '&#9827;', friendlyCode: '&#clubs;', unicode: 0x2663 },
  { value: '♥', description: 'heart', number: 9829, code: '&#9829;', friendlyCode: '&#hearts;', unicode: 0x2665 },
  { value: '♦', description: 'diamond', number: 9830, code: '&#9830;', friendlyCode: '&#diams;', unicode: 0x2666 }
] as HtmlEncoding[];

const withFriendlyCode = htmlEncodings.filter((e) => e.friendlyCode.length > 0);

export const htmlEncodingsWithFriendlyCodes = withFriendlyCode;

export const friendlyCodeToNumberCode = (s: string): string => {
  s = s.toLowerCase();
  const match = htmlEncodings.find((e) => e.friendlyCode === s.toLowerCase());

  if (!match) {
    return s;
  }

  return match.code;
};
